# Generated by Django 6.0.4 on 2026-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("greenplum", "Greenplum"),
                        ],
                        default="postgresql",
                        max_length=20,
                        verbose_name="Тип БД",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="Хост")),
                (
                    "port",
                    models.PositiveIntegerField(default=5432, verbose_name="Порт"),
                ),
                (
                    "database",
                    models.CharField(max_length=120, verbose_name="База данных"),
                ),
                (
                    "username",
                    models.CharField(max_length=120, verbose_name="Пользователь"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Подключение к БД",
                "verbose_name_plural": "Подключения к БД",
                "ordering": ["name"],
            },
        ),
    ]
