# Generated by Django 6.0.4 on 2026-08-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Создаёт таблицу, не ломая базы, ранее созданные через ``run-syncdb``."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        table = to_state.apps.get_model(app_label, self.name)._meta.db_table
        if table not in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            columns = {column.name for column in schema_editor.connection.introspection.get_table_description(cursor, model._meta.db_table)}
        if model._meta.get_field(self.name).column not in columns:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class AlterUniqueTogetherIfMissing(migrations.AlterUniqueTogether):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        expected = {tuple(item) for item in self.unique_together}
        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(cursor, model._meta.db_table)
        existing = {tuple(data["columns"]) for data in constraints.values() if data.get("unique")}
        expected_columns = {tuple(model._meta.get_field(field).column for field in item) for item in expected}
        if not expected_columns.issubset(existing):
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateModelIfMissing(
            name="DBAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="Пользователь",
                        max_length=200,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход"),
                            ("logout", "Выход"),
                            ("connection_create", "Создание подключения"),
                            ("connection_update", "Изменение подключения"),
                            ("connection_delete", "Удаление подключения"),
                            ("connection_test", "Проверка подключения"),
                            ("sidebar_settings", "Настройки сайдбара пользователя"),
                        ],
                        db_comment="Действие",
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        db_comment="Информация", verbose_name="Информация"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_comment="Дата действия", verbose_name="Дата действия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит",
                "verbose_name_plural": "Аудит",
                "db_table": "db_audit",
                "db_table_comment": "Аудит",
                "ordering": ("-created",),
            },
        ),
        CreateModelIfMissing(
            name="DBConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Дата изменения",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Активность", default=True, verbose_name="Активность"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Название", max_length=120, verbose_name="Название"
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        db_comment="Хост", max_length=255, verbose_name="Хост"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        db_comment="Порт", default=5432, verbose_name="Порт"
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        db_comment="База данных",
                        max_length=120,
                        verbose_name="База данных",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="Пользователь",
                        max_length=120,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_comment="Пароль", max_length=255, verbose_name="Пароль"
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("PostgreSQL", "PostgreSQL"),
                            ("Greenplum", "Greenplum"),
                        ],
                        db_comment="Тип базы данных",
                        default="PostgreSQL",
                        max_length=20,
                        verbose_name="Тип базы данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подключение",
                "verbose_name_plural": "Подключения",
                "db_table": "db_connection",
                "db_table_comment": "Подключение",
            },
        ),
        CreateModelIfMissing(
            name="DBUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Дата изменения",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Активность", default=True, verbose_name="Активность"
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        db_comment="Логин",
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Логин",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="Почта",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Администратор", "Администратор"),
                            ("Аналитик", "Аналитик"),
                        ],
                        db_comment="Роль",
                        default="Аналитик",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "connections",
                    models.ManyToManyField(
                        blank=True,
                        db_comment="Подключение к базе данных",
                        to="db_statistics.dbconnection",
                        verbose_name="Подключение к базе данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "db_user",
                "db_table_comment": "Пользователь",
                "ordering": ["login"],
            },
        ),
        AddFieldIfMissing(
            model_name="dbconnection",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                db_comment="Создатель подключения",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user_db_connection",
                to="db_statistics.dbuser",
                verbose_name="Создатель подключения",
            ),
        ),
        CreateModelIfMissing(
            name="UserSidebarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Дата изменения",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "visible_tabs",
                    models.JSONField(
                        blank=True,
                        db_comment="Видимые вкладки",
                        default=list,
                        verbose_name="Видимые вкладки",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sidebar_settings",
                        to="db_statistics.dbuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайдбара",
                "verbose_name_plural": "Настройки сайдбара",
                "db_table": "db_user_sidebar_settings",
                "db_table_comment": "Настройки сайдбара пользователя",
            },
        ),
        AlterUniqueTogetherIfMissing(
            name="dbconnection",
            unique_together={("name", "host", "port", "database", "username")},
        ),
        CreateModelIfMissing(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Дата изменения",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("schema", "Схема"),
                            ("table", "Таблица"),
                            ("view", "Представление"),
                            ("user", "Пользователь"),
                            ("group", "Группа"),
                        ],
                        db_comment="Тип объекта",
                        max_length=16,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        db_comment="Идентификатор объекта",
                        max_length=512,
                        verbose_name="Идентификатор объекта",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        db_comment="Подключение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="db_statistics.dbconnection",
                        verbose_name="Подключение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="db_statistics.dbuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный объект",
                "verbose_name_plural": "Избранные объекты",
                "db_table": "db_favorite",
                "db_table_comment": "Избранный объект базы данных",
                "ordering": ("object_type", "object_key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "connection", "object_type", "object_key"),
                        name="unique_user_connection_favorite",
                    )
                ],
            },
        ),
    ]
