# Generated by Django 6.0.4 on 2026-09-09 13:01

import db_statistics.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Логин пользователя, выполнившего действие.",
                        max_length=200,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход"),
                            ("logout", "Выход"),
                            ("connection_create", "Создание подключения"),
                            ("connection_update", "Изменение подключения"),
                            ("connection_delete", "Удаление подключения"),
                            ("connection_test", "Проверка подключения"),
                            ("sidebar_settings", "Настройки сайдбара пользователя"),
                            ("favorite_add", "Добавление в избранные объекты"),
                            ("favorite_remove", "Удаление из избранных объектов"),
                            ("query_terminate", "Завершение активного запроса"),
                            ("session_terminate", "Завершение активной сессии"),
                            ("vacuum", "VACUUM таблицы"),
                            ("vacuum_full", "VACUUM FULL таблицы"),
                            ("analyze", "ANALYZE таблицы"),
                            ("explain_analyze", "EXPLAIN ANALYZE таблицы"),
                        ],
                        help_text="Тип события, сохранённого в журнале аудита.",
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        help_text="Подробное безопасное описание выполненного действия.",
                        verbose_name="Информация",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        help_text="Дата и время выполнения действия.",
                        verbose_name="Дата действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит",
                "verbose_name_plural": "Аудит",
                "db_table": "db_audit",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="DBPaginationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения записи",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Количество записей на одной странице.",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Размер пагинации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пагинации",
                "verbose_name_plural": "Настройки пагинации",
                "db_table": "db_pagination_settings",
                "ordering": ("size",),
            },
        ),
        migrations.CreateModel(
            name="DBUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения записи",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, доступна ли запись для использования в приложении",
                        verbose_name="Активность",
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальное имя пользователя для входа в DB STAT",
                        max_length=100,
                        unique=True,
                        verbose_name="Логин",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Уникальный адрес электронной почты пользователя",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Администратор", "Администратор"),
                            ("Аналитик", "Аналитик"),
                        ],
                        default="Аналитик",
                        help_text="Роль определяет доступные пользователю действия в приложении",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Позволяет входить в административный сайт Django (/admin/)",
                        verbose_name="Доступ к Django admin",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество подряд неверных попыток ввода пароля с момента последнего успешного входа",
                        verbose_name="Неудачные попытки входа",
                    ),
                ),
                (
                    "lockout_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Пока не истечёт это время, вход для пользователя запрещён из-за подбора пароля",
                        null=True,
                        verbose_name="Заблокирован до",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "db_user",
                "ordering": ["login"],
            },
            managers=[
                ("objects", db_statistics.models.DBUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DBConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения записи",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, доступна ли запись для использования в приложении",
                        verbose_name="Активность",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Понятное пользователю название подключения",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Имя хоста или IP-адрес сервера базы данных",
                        max_length=255,
                        verbose_name="Хост",
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=5432,
                        help_text="TCP-порт сервера базы данных",
                        verbose_name="Порт",
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        help_text="Имя целевой базы данных для мониторинга",
                        max_length=120,
                        verbose_name="База данных",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Имя пользователя целевой базы данных",
                        max_length=120,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Зашифрованный пароль пользователя целевой базы данных.",
                        max_length=255,
                        verbose_name="Пароль",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("PostgreSQL", "PostgreSQL"),
                            ("Greenplum", "Greenplum"),
                            ("Greengage", "Greengage"),
                        ],
                        default="PostgreSQL",
                        help_text="Тип подключаемой PostgreSQL-совместимой СУБД.",
                        max_length=20,
                        verbose_name="Тип базы данных",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь DB STAT, создавший подключение.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_db_connection",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель подключения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подключение",
                "verbose_name_plural": "Подключения",
                "db_table": "db_connection",
                "unique_together": {("name", "host", "port", "database", "username")},
            },
        ),
        migrations.AddField(
            model_name="dbuser",
            name="connections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Подключения, доступные этому пользователю",
                to="db_statistics.dbconnection",
                verbose_name="Подключения к базам данных",
            ),
        ),
        migrations.CreateModel(
            name="DBUserSidebarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения записи",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "visible_tabs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Сохранённый порядок и набор доступных вкладок бокового меню",
                        verbose_name="Видимые вкладки",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Пользователь, которому принадлежат настройки бокового меню",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_db_user_sidebar_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайдбара",
                "verbose_name_plural": "Настройки сайдбара",
                "db_table": "db_user_sidebar_settings",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Уникальный идентификатор фоновой задачи.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("vacuum", "VACUUM"),
                            ("vacuum_full", "VACUUM FULL"),
                            ("analyze", "ANALYZE"),
                            ("explain_analyze", "EXPLAIN ANALYZE"),
                        ],
                        help_text="Команда обслуживания, помещённая в очередь.",
                        max_length=32,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        help_text="Имя схемы обслуживаемой таблицы.",
                        max_length=255,
                        verbose_name="Схема",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Имя обслуживаемой таблицы.",
                        max_length=255,
                        verbose_name="Таблица",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Текущее состояние задачи в устойчивой очереди.",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="Операция ожидает выполнения",
                        help_text="Текущее или итоговое сообщение исполнителя.",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Дополнительные строки результата, включая план EXPLAIN.",
                        verbose_name="Подробности",
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True,
                        help_text="Снимок статистики таблицы после выполнения операции.",
                        null=True,
                        verbose_name="Статистика",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Продолжительность выполнения операции в секундах.",
                        null=True,
                        verbose_name="Длительность, с",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Дата и время постановки задачи в очередь.",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "started",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время начала выполнения задачи.",
                        null=True,
                        verbose_name="Дата запуска",
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время успешного или ошибочного завершения задачи.",
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="Подключение к базе данных, где выполняется операция.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_jobs",
                        to="db_statistics.dbconnection",
                        verbose_name="Подключение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, запустивший операцию обслуживания.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фоновая операция обслуживания",
                "verbose_name_plural": "Фоновые операции обслуживания",
                "db_table": "db_maintenance_job",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="DBFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения записи",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("schema", "Схема"),
                            ("table", "Таблица"),
                            ("view", "Представление"),
                            ("function", "Функция"),
                            ("user", "Пользователь"),
                            ("group", "Группа"),
                        ],
                        help_text="Категория избранного объекта базы данных",
                        max_length=16,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        help_text="Стабильный составной ключ объекта внутри подключения",
                        max_length=512,
                        verbose_name="Идентификатор объекта",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="Подключение, в котором находится избранный объект",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_db_favorite",
                        to="db_statistics.dbconnection",
                        verbose_name="Подключение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, добавивший объект в избранное",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_db_favorite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный объект",
                "verbose_name_plural": "Избранные объекты",
                "db_table": "db_favorite",
                "ordering": ("object_type", "object_key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "connection", "object_type", "object_key"),
                        name="unique_user_connection_favorite",
                    )
                ],
            },
        ),
    ]
