# Generated by Django 6.0.4 on 2026-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersidebarsettings",
            name="favorite_connections",
            field=models.JSONField(
                blank=True,
                db_comment="Избранные подключения",
                default=list,
                verbose_name="Избранные подключения",
            ),
        ),
        migrations.AddField(
            model_name="usersidebarsettings",
            name="favorite_tables",
            field=models.JSONField(
                blank=True,
                db_comment="Избранные таблицы",
                default=list,
                verbose_name="Избранные таблицы",
            ),
        ),
    ]
