# Generated by Django 6.0.4 on 2026-08-29 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("vacuum", "VACUUM"),
                            ("vacuum_full", "VACUUM FULL"),
                            ("analyze", "ANALYZE"),
                            ("explain_analyze", "EXPLAIN ANALYZE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(default="Операция ожидает выполнения")),
                ("details", models.JSONField(blank=True, default=list)),
                ("statistics", models.JSONField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_jobs",
                        to="db_statistics.dbconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_jobs",
                        to="db_statistics.dbuser",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_job",
                "ordering": ("-created",),
            },
        ),
    ]
