# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbaudit",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("logout", "Выход"),
                    ("connection_create", "Создание подключения"),
                    ("connection_update", "Изменение подключения"),
                    ("connection_delete", "Удаление подключения"),
                    ("connection_test", "Проверка подключения"),
                    ("sidebar_settings", "Настройки сайдбара пользователя"),
                ],
                db_comment="Действие",
                max_length=32,
                verbose_name="Действие",
            ),
        ),
    ]
