# Generated by Django 6.0.4 on 2026-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersidebarsettings",
            name="visible_audit_actions",
            field=models.JSONField(
                blank=True,
                db_comment="Видимые действия аудита",
                default=list,
                verbose_name="Видимые действия аудита",
            ),
        ),
    ]
