# Generated by Django 6.0.4 on 2026-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0002_usersidebarsettings_favorite_connections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersidebarsettings",
            name="favorite_schemas",
            field=models.JSONField(
                blank=True,
                db_comment="Избранные схемы",
                default=list,
                verbose_name="Избранные схемы",
            ),
        ),
    ]
