# Generated by Django 6.0.4 on 2026-08-30 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0002_maintenancejob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancejob",
            options={
                "ordering": ("-created",),
                "verbose_name": "Фоновая операция обслуживания",
                "verbose_name_plural": "Фоновые операции обслуживания",
            },
        ),
        migrations.AlterField(
            model_name="dbaudit",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("logout", "Выход"),
                    ("connection_create", "Создание подключения"),
                    ("connection_update", "Изменение подключения"),
                    ("connection_delete", "Удаление подключения"),
                    ("connection_test", "Проверка подключения"),
                    ("sidebar_settings", "Настройки сайдбара пользователя"),
                    ("favorite_add", "Добавление в избранные объекты"),
                    ("favorite_remove", "Удаление из избранных объектов"),
                    ("query_terminate", "Завершение активного запроса"),
                    ("session_terminate", "Завершение активной сессии"),
                    ("vacuum", "VACUUM таблицы"),
                    ("vacuum_full", "VACUUM FULL таблицы"),
                    ("analyze", "ANALYZE таблицы"),
                    ("explain_analyze", "EXPLAIN ANALYZE таблицы"),
                ],
                help_text="Тип события, сохранённого в журнале аудита.",
                max_length=32,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="dbaudit",
            name="created",
            field=models.DateTimeField(
                help_text="Дата и время выполнения действия.",
                verbose_name="Дата действия",
            ),
        ),
        migrations.AlterField(
            model_name="dbaudit",
            name="info",
            field=models.TextField(
                help_text="Подробное безопасное описание выполненного действия.",
                verbose_name="Информация",
            ),
        ),
        migrations.AlterField(
            model_name="dbaudit",
            name="username",
            field=models.CharField(
                help_text="Логин пользователя, выполнившего действие.",
                max_length=200,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь DB STAT, создавший подключение.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user_db_connection",
                to="db_statistics.dbuser",
                verbose_name="Создатель подключения",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="database",
            field=models.CharField(
                help_text="Имя целевой базы данных для мониторинга.",
                max_length=120,
                verbose_name="База данных",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("Greenplum", "Greenplum"),
                    ("Greengage", "Greengage"),
                ],
                default="PostgreSQL",
                help_text="Тип подключаемой PostgreSQL-совместимой СУБД.",
                max_length=20,
                verbose_name="Тип базы данных",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="host",
            field=models.CharField(
                help_text="Имя хоста или IP-адрес сервера базы данных.",
                max_length=255,
                verbose_name="Хост",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, доступна ли запись для использования в приложении.",
                verbose_name="Активность",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="name",
            field=models.CharField(
                help_text="Понятное пользователю название подключения.",
                max_length=120,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="password",
            field=models.CharField(
                help_text="Зашифрованный пароль пользователя целевой базы данных.",
                max_length=255,
                verbose_name="Пароль",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="port",
            field=models.PositiveIntegerField(
                default=5432,
                help_text="TCP-порт сервера базы данных.",
                verbose_name="Порт",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения записи.",
                verbose_name="Дата изменения",
            ),
        ),
        migrations.AlterField(
            model_name="dbconnection",
            name="username",
            field=models.CharField(
                help_text="Имя пользователя целевой базы данных.",
                max_length=120,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="connection",
            field=models.ForeignKey(
                help_text="Подключение, в котором находится избранный объект.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_db_favorite",
                to="db_statistics.dbconnection",
                verbose_name="Подключение",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="object_key",
            field=models.CharField(
                help_text="Стабильный составной ключ объекта внутри подключения.",
                max_length=512,
                verbose_name="Идентификатор объекта",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("schema", "Схема"),
                    ("table", "Таблица"),
                    ("view", "Представление"),
                    ("function", "Функция"),
                    ("user", "Пользователь"),
                    ("group", "Группа"),
                ],
                help_text="Категория избранного объекта базы данных.",
                max_length=16,
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения записи.",
                verbose_name="Дата изменения",
            ),
        ),
        migrations.AlterField(
            model_name="dbfavorite",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, добавивший объект в избранное.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_db_favorite",
                to="db_statistics.dbuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="connections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Подключения, доступные этому пользователю.",
                to="db_statistics.dbconnection",
                verbose_name="Подключения к базам данных",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="email",
            field=models.EmailField(
                help_text="Уникальный адрес электронной почты пользователя.",
                max_length=254,
                unique=True,
                verbose_name="Почта",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, доступна ли запись для использования в приложении.",
                verbose_name="Активность",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="login",
            field=models.CharField(
                db_index=True,
                help_text="Уникальное имя пользователя для входа в DB STAT.",
                max_length=100,
                unique=True,
                verbose_name="Логин",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="role",
            field=models.CharField(
                choices=[("Администратор", "Администратор"), ("Аналитик", "Аналитик")],
                default="Аналитик",
                help_text="Роль определяет доступные пользователю действия.",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="dbuser",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения записи.",
                verbose_name="Дата изменения",
            ),
        ),
        migrations.AlterField(
            model_name="dbusersidebarsettings",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="dbusersidebarsettings",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения записи.",
                verbose_name="Дата изменения",
            ),
        ),
        migrations.AlterField(
            model_name="dbusersidebarsettings",
            name="user",
            field=models.OneToOneField(
                help_text="Пользователь, которому принадлежат настройки бокового меню.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_db_user_sidebar_settings",
                to="db_statistics.dbuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="dbusersidebarsettings",
            name="visible_tabs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Сохранённый порядок и набор доступных вкладок бокового меню.",
                verbose_name="Видимые вкладки",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="connection",
            field=models.ForeignKey(
                help_text="Подключение к базе данных, где выполняется операция.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_jobs",
                to="db_statistics.dbconnection",
                verbose_name="Подключение",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Дата и время постановки задачи в очередь.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Дополнительные строки результата, включая план EXPLAIN.",
                verbose_name="Подробности",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="duration_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Продолжительность выполнения операции в секундах.",
                null=True,
                verbose_name="Длительность, с",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="finished",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время успешного или ошибочного завершения задачи.",
                null=True,
                verbose_name="Дата завершения",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Уникальный идентификатор фоновой задачи.",
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="message",
            field=models.TextField(
                default="Операция ожидает выполнения",
                help_text="Текущее или итоговое сообщение исполнителя.",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="operation",
            field=models.CharField(
                choices=[
                    ("vacuum", "VACUUM"),
                    ("vacuum_full", "VACUUM FULL"),
                    ("analyze", "ANALYZE"),
                    ("explain_analyze", "EXPLAIN ANALYZE"),
                ],
                help_text="Команда обслуживания, помещённая в очередь.",
                max_length=32,
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="schema_name",
            field=models.CharField(
                help_text="Имя схемы обслуживаемой таблицы.",
                max_length=255,
                verbose_name="Схема",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="started",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время начала выполнения задачи.",
                null=True,
                verbose_name="Дата запуска",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="statistics",
            field=models.JSONField(
                blank=True,
                help_text="Снимок статистики таблицы после выполнения операции.",
                null=True,
                verbose_name="Статистика",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "В очереди"),
                    ("running", "Выполняется"),
                    ("completed", "Завершено"),
                    ("failed", "Ошибка"),
                ],
                db_index=True,
                default="queued",
                help_text="Текущее состояние задачи в устойчивой очереди.",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="table_name",
            field=models.CharField(
                help_text="Имя обслуживаемой таблицы.",
                max_length=255,
                verbose_name="Таблица",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancejob",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, запустивший операцию обслуживания.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_jobs",
                to="db_statistics.dbuser",
                verbose_name="Пользователь",
            ),
        ),
    ]
