# Generated by Django 6.0.4 on 2026-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0003_rename_models_and_related_names"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="dbfavorite",
            table_comment="Избранный объект",
        ),
        migrations.AlterModelTableComment(
            name="dbusersidebarsettings",
            table_comment="Настройки сайдбара",
        ),
        migrations.AlterField(
            model_name="dbaudit",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("logout", "Выход"),
                    ("connection_create", "Создание подключения"),
                    ("connection_update", "Изменение подключения"),
                    ("connection_delete", "Удаление подключения"),
                    ("connection_test", "Проверка подключения"),
                    ("sidebar_settings", "Настройки сайдбара пользователя"),
                    ("favorite_add", "Добавление в избранные объекты"),
                ],
                db_comment="Действие",
                max_length=32,
                verbose_name="Действие",
            ),
        ),
    ]
