# Generated by Django 6.0.4 on 2026-09-09 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0003_add_default_pagination_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbpaginationsettings",
            name="size",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Количество записей на одной странице.",
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Размер пагинации",
            ),
        ),
    ]
