# Generated by Django 6.0.4 on 2026-08-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_statistics", "0003_alter_maintenancejob_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="maintenancejob",
            table="db_maintenance_job",
        ),
    ]
