from django.urls import path, re_path

from db_statistics.views import additional, administration, data, infrastructure, performance

urlpatterns = [
    path("healthz/", additional.healthz, name="healthz"),
    path("", additional.home, name="home"),
    path("login/", additional.login, name="login"),
    path("logout/", additional.logout, name="logout"),
    path("audit/events/", additional.audit_events, name="audit_events"),
    path("settings/sidebar/", additional.sidebar_settings, name="sidebar_settings"),
    path("settings/language/", additional.language_settings, name="language_settings"),
    path("settings/pagination/", additional.pagination_settings, name="pagination_settings"),
    path("favorites/", additional.favorites, name="favorites"),
    path("connections/", additional.connections, name="connections"),
    path("connections/test/", additional.test_connection, name="test_connection"),
    path("connections/delete/", additional.delete_connection, name="delete_connection"),
    path("databases/overview/", infrastructure.database_overview, name="database_overview"),
    path("databases/schemas/", data.database_schema_sizes, name="database_schema_sizes"),
    path("tables/sizes/", data.database_table_sizes, name="database_table_sizes"),
    path("views/list/", data.database_views_list, name="database_views_list"),
    path("functions/list/", data.database_functions_list, name="database_functions_list"),
    path("distribution/tables/", data.distribution_tables, name="distribution_tables"),
    path("distribution/info/", data.distribution_info, name="distribution_info"),
    path("temp-tables/sizes/", data.database_temp_table_sizes, name="database_temp_table_sizes"),
    path("temp-tables/delete/", data.delete_temp_table, name="delete_temp_table"),
    path("queries/active/", performance.active_queries, name="active_queries"),
    path("queries/terminate/", performance.terminate_active_query, name="terminate_active_query"),
    path("sessions/active/", performance.active_sessions, name="active_sessions"),
    path("sessions/terminate/", performance.terminate_active_session, name="terminate_active_session"),
    path("locks/blocking/", performance.blocking_locks, name="blocking_locks"),
    path("transactions/idle/", performance.idle_transactions, name="idle_transactions"),
    path("memory/overview/", administration.memory_overview, name="memory_overview"),
    path("maintenance/stats/", administration.maintenance_stats, name="maintenance_stats"),
    path("maintenance/vacuum/", administration.maintenance_operation, name="maintenance_vacuum"),
    path("maintenance/operation/", administration.maintenance_operation, name="maintenance_operation"),
    path("maintenance/jobs/", administration.maintenance_jobs, name="maintenance_jobs"),
    path("users/list/", administration.database_users_list, name="database_users_list"),
    path("groups/list/", administration.database_groups_list, name="database_groups_list"),
    path("segments/info/", infrastructure.segments_info, name="segments_info"),
    # Последний маршрут позволяет проверять фирменную 404-страницу и при DEBUG=True.
    re_path(r"^.*$", additional.page_not_found, name="page_not_found"),
]
